version: "2"
services:
  backend:
    build: .
    container_name: url-shortener
    command: npm run server
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
